version: '2.1'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/app/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: psql -U postgres -c --
      interval: 10s
      retries: 10
      timeout: 1m30s
    ports:
      - "54321:5432"