version: '2.1'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/app/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      db:
        condition: service_healthy
      # mongodb:
      #   condition: service_healthy
    links:
    - mongodb
    ports:
      - "8080:8080"

  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: psql -U postgres -c --
      interval: 10s
      retries: 10
      timeout: 1m30s
    ports:
      - "54321:5432"

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    # healthcheck:
    #   test: echo 'db.stats().ok' | mongo localhost:27017/hw7 --quiet
    #   interval: 5s
    #   timeout: 5s
    #   retries: 12
    environment:
      - MONGODB_PASS=mongo
    ports:
        - 27027:27017
